{{- range $application_name, $application := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $application_name }}
  namespace: sys-argocd
spec:
  project: default
  source:
    repoURL: {{ $application.repoURL }}
    targetRevision: {{ $application.targetRevision }}
    {{- if $application.path }}
    {{- if $application.directoryRecurse }}
    directory:
      recurse: true
    {{ end }}
    path: {{ $application.path }}
    {{ end }}
    chart: {{ $application.chart }}
    {{- if $application.values }}
    helm:
      values: |-
      {{- $application.values | nindent 8 }}
    {{- end }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ $application_name }}
  syncPolicy:
  {{- if $application.syncEnabled }}
    automated:
      prune: true
      selfHeal: true
   {{ end }}
    syncOptions:
      - CreateNamespace=true
   {{- if $application.replace }}
      - Replace=true
  {{- end }}
{{- end }}